"""Application-layer protocols (ports) for the profile bounded context."""

from __future__ import annotations

from typing import Any, Protocol


class ProfileRepository(Protocol):
    """Everything the profile use cases need from the outside world.

    Concrete implementations live in :mod:`untaped_profile.infrastructure`;
    tests use an in-memory fake. The contract is intentionally narrow —
    every method is either a query or a single-step mutation.
    """

    def names(self) -> list[str]: ...
    def active_name(self) -> str | None: ...
    def persisted_active_name(self) -> str | None: ...
    def read(self, name: str) -> dict[str, Any] | None: ...
    def resolved(self, name: str) -> dict[str, Any]: ...
    def write(self, name: str, data: dict[str, Any]) -> None: ...
    def delete(self, name: str) -> bool: ...
    def set_active(self, name: str) -> None: ...
